---
pipeline: 
 pipeline_name: scd2_full_load
 instance_name: BT-FV-tr-tst-cdf-instance
 location: europe-west1
 runtime_args: {
  'GCS_Input_Path':'gs://BTFV-trdh-rawingested-map-tstnonlive/nc/vhtma_21000_rdb/demo_table_1/processing/*/*demo_table_1*',
  'header':':ACCOUNT_SDAAA,:SDSDSD_BILL_SDD,:SDSDSD_BILL_SDD,:ACCOUNTsSS,:CATED_M,:NOTES_TMC',
  'column_comparision':'IFNULL(SRC.ACCOUNT_SDAAA,"###") <> IFNULL(TGT.ACCOUNT_SDAAA ,"###") OR
 IFNULL(SRC.SDSDSD_BILL_SDD,-9999) <> IFNULL(TGT.SDSDSD_BILL_SDD ,-9999) OR
 IFNULL(SRC.ACCOUNTsSS,-9999) <> IFNULL(TGT.ACCOUNTsSS ,-9999) OR
 IFNULL(SRC.CATED_M,-9999) <> IFNULL(TGT.CATED_M ,-9999) OR
 IFNULL(SRC.NOTES_TMC,"###") <> IFNULL(TGT.NOTES_TMC ,"###")',
  'column_comparision_tgt':'IFNULL(SRC_T.ACCOUNT_SDAAA ,"###") <> IFNULL(TGT_T.ACCOUNT_SDAAA ,"###") OR
 IFNULL(SRC_T.SDSDSD_BILL_SDD ,-9999) <> IFNULL(TGT_T.SDSDSD_BILL_SDD ,-9999) OR
 IFNULL(SRC_T.SDSDSD_BILL_SDD ,-9999) <> IFNULL(TGT_T.SDSDSD_BILL_SDD ,-9999) OR
 IFNULL(SRC_T.ACCOUNTsSS ,-9999) <> IFNULL(TGT_T.ACCOUNTsSS ,-9999) OR
 IFNULL(SRC_T.CATED_M ,-9999) <> IFNULL(TGT_T.CATED_M ,-9999) OR
 IFNULL(SRC_T.NOTES_TMC ,"###") <> IFNULL(TGT_T.NOTES_TMC ,"###")',
  'null_id':'NULL AS JOINKEY1,NULL AS JOINKEY2,NULL AS JOINKEY3',
  'merge_condition':'SRC_T.JOINKEY1=TGT_T.ACCOUNT_SDAAA AND SRC_T.JOINKEY2=TGT_T.SDSDSD_BILL_SDD AND SRC_T.JOINKEY3=TGT_T.SDSDSD_BILL_SDD',
  'src_fields':'SRC.ACCOUNT_SDAAA,SRC.SDSDSD_BILL_SDD,SRC.SDSDSD_BILL_SDD,SRC.ACCOUNTsSS,SRC.CATED_M,SRC.NOTES_TMC,SRC.TR_FILE_ID,SRC.TR_INSERT_DATETIME,SRC.TR_INSERT_ID,SRC.TR_UPDATE_DATETIME,SRC.TR_UPDATE_ID,SRC.START_OF_VALIDITY,SRC.END_OF_VALIDITY,SRC.ACTIVE_FL',
  'join_condition':'SRC.ACCOUNT_SDAAA=TGT.ACCOUNT_SDAAA AND SRC.SDSDSD_BILL_SDD=TGT.SDSDSD_BILL_SDD AND SRC.SDSDSD_BILL_SDD=TGT.SDSDSD_BILL_SDD',
  'id':'ACCOUNT_SDAAA AS JOINKEY1,SDSDSD_BILL_SDD AS JOINKEY2,SDSDSD_BILL_SDD AS JOINKEY3',
  'fields':'ACCOUNT_SDAAA,SDSDSD_BILL_SDD,SDSDSD_BILL_SDD,ACCOUNTsSS,CATED_M,NOTES_TMC,TR_FILE_ID,TR_INSERT_DATETIME,TR_INSERT_ID,TR_UPDATE_DATETIME,TR_UPDATE_ID,START_OF_VALIDITY,END_OF_VALIDITY,ACTIVE_FL',
  'recipe':'demo_table_1_recipe.txt',
  'gcs.project':'BT-FV-tr-tst-non-live',
  'bq.project':'BT-FV-tr-tst-non-live',
  'bq.TempStorage':'BTFV-trdh-map-nonlive1',
  'bq.table':'demo_table_1',
  'bq.stage_table':'stg_demo_table_1',
  'bq.dataset':'bq_dataset_name',
  'schema':'demo_table_1_schema.txt'
  }
---
pipeline: 
 pipeline_name: scd2_full_load
 instance_name: BT-FV-tr-tst-cdf-instance
 location: europe-west1
 runtime_args: {
  'GCS_Input_Path':'gs://BTFV-trdh-rawingested-map-tstnonlive/nc/vhtma_21000_rdb/Demo_2/processing/*/*Demo_2*',
  'header':':TAILOR,:ION_TAIL,:PEC_IDSS,:AMOUNT_DF,:MIN_AM,:MAX_AM,:TIK_TOK_DEMO,:PRORATE,:CODE_RED',
  'column_comparision':'IFNULL(SRC.TAILOR,-9999) <> IFNULL(TGT.TAILOR ,-9999) OR
 IFNULL(SRC.ION_TAIL,-9999) <> IFNULL(TGT.ION_TAIL ,-9999) OR
 IFNULL(SRC.PEC_IDSS,-9999) <> IFNULL(TGT.PEC_IDSS ,-9999) OR
 IFNULL(SRC.AMOUNT_DF,-9999.99) <> IFNULL(TGT.AMOUNT_DF ,-9999.99) OR
 IFNULL(SRC.MIN_AM,-9999.99) <> IFNULL(TGT.MIN_AM ,-9999.99) OR
 IFNULL(SRC.MAX_AM,-9999.99) <> IFNULL(TGT.MAX_AM ,-9999.99) OR
 IFNULL(SRC.TIK_TOK_DEMO,-9999) <> IFNULL(TGT.TIK_TOK_DEMO ,-9999) OR
 IFNULL(SRC.PRORATE,-9999) <> IFNULL(TGT.PRORATE ,-9999) OR
 IFNULL(SRC.CODE_RED,-9999) <> IFNULL(TGT.CODE_RED ,-9999)',
  'column_comparision_tgt':'IFNULL(SRC_T.TAILOR ,-9999) <> IFNULL(TGT_T.TAILOR ,-9999) OR
 IFNULL(SRC_T.ION_TAIL ,-9999) <> IFNULL(TGT_T.ION_TAIL ,-9999) OR
 IFNULL(SRC_T.PEC_IDSS ,-9999) <> IFNULL(TGT_T.PEC_IDSS ,-9999) OR
 IFNULL(SRC_T.AMOUNT_DF ,-9999.99) <> IFNULL(TGT_T.AMOUNT_DF ,-9999.99) OR
 IFNULL(SRC_T.MIN_AM ,-9999.99) <> IFNULL(TGT_T.MIN_AM ,-9999.99) OR
 IFNULL(SRC_T.MAX_AM ,-9999.99) <> IFNULL(TGT_T.MAX_AM ,-9999.99) OR
 IFNULL(SRC_T.TIK_TOK_DEMO ,-9999) <> IFNULL(TGT_T.TIK_TOK_DEMO ,-9999) OR
 IFNULL(SRC_T.PRORATE ,-9999) <> IFNULL(TGT_T.PRORATE ,-9999) OR
 IFNULL(SRC_T.CODE_RED ,-9999) <> IFNULL(TGT_T.CODE_RED ,-9999)',
  'null_id':'NULL AS JOINKEY1',
  'merge_condition':'SRC_T.JOINKEY1=TGT_T.TAILOR',
  'src_fields':'SRC.TAILOR,SRC.ION_TAIL,SRC.PEC_IDSS,SRC.AMOUNT_DF,SRC.MIN_AM,SRC.MAX_AM,SRC.TIK_TOK_DEMO,SRC.PRORATE,SRC.CODE_RED,SRC.TR_FILE_ID,SRC.TR_INSERT_DATETIME,SRC.TR_INSERT_ID,SRC.TR_UPDATE_DATETIME,SRC.TR_UPDATE_ID,SRC.START_OF_VALIDITY,SRC.END_OF_VALIDITY,SRC.ACTIVE_FL',
  'join_condition':'SRC.TAILOR=TGT.TAILOR',
  'id':'TAILOR AS JOINKEY1',
  'fields':'TAILOR,ION_TAIL,PEC_IDSS,AMOUNT_DF,MIN_AM,MAX_AM,TIK_TOK_DEMO,PRORATE,CODE_RED,TR_FILE_ID,TR_INSERT_DATETIME,TR_INSERT_ID,TR_UPDATE_DATETIME,TR_UPDATE_ID,START_OF_VALIDITY,END_OF_VALIDITY,ACTIVE_FL',
  'recipe':'Demo_2_recipe.txt',
  'gcs.project':'BT-FV-tr-tst-non-live',
  'bq.project':'BT-FV-tr-tst-non-live',
  'bq.TempStorage':'BTFV-trdh-map-nonlive1',
  'bq.table':'Demo_2',
  'bq.stage_table':'stg_Demo_2',
  'bq.dataset':'Demo_2',
  'schema':'Demo_2_schema.txt'
  }
---
pipeline: 
 pipeline_name: scd2_full_load
 instance_name: BT-FV-tr-tst-cdf-instance
 location: europe-west1
 runtime_args: {
  'GCS_Input_Path':'gs://BTFV-trdh-rawingested-map-tstnonlive/nc/nc/demo_table_3/processing/*/*demo_table_3*',
  'header':':TIK_TOK_DEMO,:CONDITION_SET_ID',
  'column_comparision':'IFNULL(SRC.TIK_TOK_DEMO,-9999) <> IFNULL(TGT.TIK_TOK_DEMO ,-9999) OR
 IFNULL(SRC.CONDITION_SET_ID,-9999) <> IFNULL(TGT.CONDITION_SET_ID ,-9999)',
  'column_comparision_tgt':'IFNULL(SRC_T.TIK_TOK_DEMO ,-9999) <> IFNULL(TGT_T.TIK_TOK_DEMO ,-9999) OR
 IFNULL(SRC_T.CONDITION_SET_ID ,-9999) <> IFNULL(TGT_T.CONDITION_SET_ID ,-9999)',
  'null_id':'NULL AS JOINKEY1,NULL AS JOINKEY2',
  'merge_condition':'SRC_T.JOINKEY1=TGT_T.TIK_TOK_DEMO AND SRC_T.JOINKEY2=TGT_T.CONDITION_SET_ID',
  'src_fields':'SRC.TIK_TOK_DEMO,SRC.CONDITION_SET_ID,SRC.TR_FILE_ID,SRC.TR_INSERT_DATETIME,SRC.TR_INSERT_ID,SRC.TR_UPDATE_DATETIME,SRC.TR_UPDATE_ID,SRC.START_OF_VALIDITY,SRC.END_OF_VALIDITY,SRC.ACTIVE_FL',
  'join_condition':'SRC.TIK_TOK_DEMO=TGT.TIK_TOK_DEMO AND SRC.CONDITION_SET_ID=TGT.CONDITION_SET_ID',
  'id':'TIK_TOK_DEMO AS JOINKEY1,CONDITION_SET_ID AS JOINKEY2',
  'fields':'TIK_TOK_DEMO,CONDITION_SET_ID,TR_FILE_ID,TR_INSERT_DATETIME,TR_INSERT_ID,TR_UPDATE_DATETIME,TR_UPDATE_ID,START_OF_VALIDITY,END_OF_VALIDITY,ACTIVE_FL',
  'recipe':'demo_table_3_recipe.txt',
  'gcs.project':'BT-FV-tr-tst-non-live',
  'bq.project':'BT-FV-tr-tst-non-live',
  'bq.TempStorage':'BTFV-trdh-map-nonlive1',
  'bq.table':'demo_table_3',
  'bq.stage_table':'stg_demo_table_3',
  'bq.dataset':'Demo_2',
  'schema':'demo_table_3_schema.txt'
  }
...
